/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacio;

/**
 *
 * @author guill
 */
public class MenuUsuariPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuUsuariPanel
     */
    public MenuUsuariPanel() {
        initComponents();
       // setNomUsuari();
    }
    
    public void setNomUsuari(String nom) {
        nomUser.setText(nom);
    }
    
    public void mostrarMenuUsuari() {
        /*if (actFrame != null) {
            actFrame.dispose();
        }
        VistaMenuUsuari vista = new VistaMenuUsuari();
        MenuUsuariPanel menuPanel = vista.getMenuPanel();
        String nomUsuari = nomUsuariActual(); // Obtener el nombre del usuario actual
        menuPanel.setNomUsuari(nomUsuari); // Establecer el nombre en el panel
        actFrame = vista;
        actFrame.setVisible(true);*/
    }
    
   // public MenuUsuariPanel getMenuPanel() {
      //  return MenuUsuariPanel; // Asume que el panel se llama menuUsuariPanel
   // }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonChange = new javax.swing.JButton();
        FotoUser = new javax.swing.JLabel();
        nomUser = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 242, 239));

        jLabel1.setText("Nom d'usuari:");

        buttonChange.setText("Cambiar contrassenya");
        buttonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeActionPerformed(evt);
            }
        });

        FotoUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\guill\\Desktop\\Cosas_Uni\\Prop\\proj2\\subgrup-prop41.1\\FONTS\\src\\main\\resources\\img\\personIcon.png")); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(FotoUser)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(nomUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buttonChange)
                        .addGap(102, 102, 102))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nomUser))
                        .addGap(18, 18, 18)
                        .addComponent(buttonChange))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(FotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeActionPerformed
        String newPassword = javax.swing.JOptionPane.showInputDialog(this, "Introdueix la nova contrassenya:");
        if (newPassword != null && !newPassword.trim().isEmpty()) {
            CtrlPresentacio ctrlPresentacio = new CtrlPresentacio(); // Instancia del controlador
            String username = ctrlPresentacio.nomUsuariActual(); // Obtener el nombre del usuario actual
            ctrlPresentacio.canviarContrasenya(username, newPassword); // Cambiar contraseña
        }  
    }//GEN-LAST:event_buttonChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FotoUser;
    private javax.swing.JPanel background;
    private javax.swing.JButton buttonChange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomUser;
    // End of variables declaration//GEN-END:variables
}
