/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacio;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JCheckBox;
import javax.swing.JPanel;

/**
 *
 * @author hajweriahussain
 */
public class VistaCrearPrestatgeria extends javax.swing.JPanel {
    /**
     * Creates new form vistaCrearPrestatgeria
     * 
     */
        private CardLayout cardLayout;
        private JPanel cardPanel;
        private CtrlPresentacio cp;
        
    public VistaCrearPrestatgeria() {
        
        initComponents();
        cp = new CtrlPresentacio();
        initComponents();
        this.setSize(600, 400);
        cardLayout = (CardLayout) this.getLayout();
        cargarProductosEnScrollPane();
    }
    
    public void cargarProductosEnScrollPane(){
        Set<Integer> idsProductos = new HashSet<>(Arrays.asList(101, 102, 103, 104, 105, 106, 107, 
                                                    108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
                                                    118, 119, 120, 121, 122, 123, 124, 125));
//        Set<Integer> idsProductos = cp.mostrarProductes();
        panelGrid.setLayout(new GridLayout(0, 4, 10, 10));
        for (Integer id : idsProductos) {
            JCheckBox checkBox = new JCheckBox(String.valueOf(id)); // Usa el ID como texto
            panelGrid.add(checkBox);           // Añade el checkbox al panel
        }

        // Añadir el panel al JScrollPane
        panelProductos.setViewportView(panelGrid);
    }
    
    
    private Boolean validarID() {
        String texto = Idtxt.getText().trim();
//
        if (texto.isEmpty()) {
            errorId.setText("Error: El camp no pot estar buit.");
            return false;
        }
        try {
            int id = Integer.parseInt(texto); // Intenta convertir a número
            if (id < 0) { // Opcional: verifica si es un número positivo
                errorId.setText("Error: El identificador ha de ser un número positiu.");
                return false;
            }
            else {
                errorId.setText("Entrada válida."); // Todo está bien
                errorId.setForeground(Color.GREEN); // Cambia el color si es válido
            }
        } catch (NumberFormatException e) {
            errorId.setText("Error: Introdueix un número vàlid.");
            errorId.setForeground(Color.RED); // Asegura el color de error
            return false;
        }
        return true;
    }
    
    
    private Boolean validarNom() {
        String texto = nomtxt.getText().trim();

        if (texto.isEmpty()) {
            errorNom.setText("Error: El camp no pot estar buit.");
            errorNom.setForeground(Color.RED);
            return false;
        }

        // Si el texto es válido (es un nombre), se limpia el mensaje de error
        errorNom.setText("Entrada vàlida.");
        errorNom.setForeground(Color.GREEN);
        return true;
    }
    
    private Boolean validarNumColumnes() {
        String texto = colstxt.getText().trim();

        if (texto.isEmpty()) {
            errorNcols.setText("Error: El camp no pot estar buit.");
            errorNcols.setForeground(Color.RED);
            return false;
        }

        try {
            int numFilas = Integer.parseInt(texto); // Intenta convertir a un número
            if (numFilas <= 0) { // Verifica que sea un número positivo
                errorNcols.setText("Error: El número de files ha de ser major que 0.");
                errorNcols.setForeground(Color.RED);
                return false;
            } else {
                errorNcols.setText("Entrada válida.");
                errorNcols.setForeground(Color.GREEN);
                
            }
        } catch (NumberFormatException e) {
            errorNcols.setText("Error: Ha de ser un número enter positiu.");
            errorNcols.setForeground(Color.RED);
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        page1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        IdLabel = new javax.swing.JLabel();
        nColsLabel = new javax.swing.JLabel();
        Idtxt = new javax.swing.JTextField();
        nomLabel = new javax.swing.JLabel();
        nomtxt = new javax.swing.JTextField();
        colstxt = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnSortir = new javax.swing.JButton();
        errorId = new javax.swing.JLabel();
        errorNom = new javax.swing.JLabel();
        errorNcols = new javax.swing.JLabel();
        page2 = new javax.swing.JPanel();
        productesLabel = new javax.swing.JLabel();
        panelProductos = new javax.swing.JScrollPane();
        panelGrid = new javax.swing.JPanel();
        algoritmeLabel = new javax.swing.JLabel();
        btnBF = new javax.swing.JRadioButton();
        btnDosAp = new javax.swing.JRadioButton();
        btnSortir2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.CardLayout());

        page1.setBackground(new java.awt.Color(255, 255, 255));
        page1.setPreferredSize(new java.awt.Dimension(600, 400));
        page1.setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        title.setText("Crear Prestatgeria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 54, 0, 0);
        page1.add(title, gridBagConstraints);

        IdLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        IdLabel.setText("Identificador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 84, 0, 0);
        page1.add(IdLabel, gridBagConstraints);

        nColsLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        nColsLabel.setText("Nombre de columnes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 84, 0, 0);
        page1.add(nColsLabel, gridBagConstraints);

        Idtxt.setForeground(new java.awt.Color(153, 153, 153));
        Idtxt.setText("Introdueix un identificador numeric");
        Idtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IdtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IdtxtFocusLost(evt);
            }
        });
        Idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdtxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 84, 0, 0);
        page1.add(Idtxt, gridBagConstraints);

        nomLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        nomLabel.setText("Nom");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 84, 0, 0);
        page1.add(nomLabel, gridBagConstraints);

        nomtxt.setForeground(new java.awt.Color(153, 153, 153));
        nomtxt.setText("Introdueix un nom");
        nomtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomtxtFocusLost(evt);
            }
        });
        nomtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomtxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 84, 0, 0);
        page1.add(nomtxt, gridBagConstraints);

        colstxt.setForeground(new java.awt.Color(153, 153, 153));
        colstxt.setText("Introdueix el nombre de columnes");
        colstxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                colstxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                colstxtFocusLost(evt);
            }
        });
        colstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colstxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 84, 0, 0);
        page1.add(colstxt, gridBagConstraints);

        btnCrear.setText("Següent");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(109, 85, 29, 18);
        page1.add(btnCrear, gridBagConstraints);

        btnSortir.setBackground(new java.awt.Color(153, 153, 153));
        btnSortir.setText("X");
        btnSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 137, 0, 18);
        page1.add(btnSortir, gridBagConstraints);

        errorId.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        errorId.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 236;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 84, 0, 0);
        page1.add(errorId, gridBagConstraints);

        errorNom.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 236;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 84, 0, 0);
        page1.add(errorNom, gridBagConstraints);

        errorNcols.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 236;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 84, 0, 0);
        page1.add(errorNcols, gridBagConstraints);

        add(page1, "card2");

        page2.setBackground(new java.awt.Color(255, 255, 255));
        page2.setLayout(new java.awt.GridBagLayout());

        productesLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        productesLabel.setText("Productes a afegir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 60, 0, 0);
        page2.add(productesLabel, gridBagConstraints);

        panelGrid.setBackground(new java.awt.Color(255, 255, 255));
        panelGrid.setLayout(new java.awt.GridLayout(1, 0));
        panelProductos.setViewportView(panelGrid);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 341;
        gridBagConstraints.ipady = 149;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 60, 0, 0);
        page2.add(panelProductos, gridBagConstraints);

        algoritmeLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        algoritmeLabel.setText("Algoritme a utilitzar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 60, 0, 0);
        page2.add(algoritmeLabel, gridBagConstraints);

        btnBF.setText("Força Bruta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 60, 169, 0);
        page2.add(btnBF, gridBagConstraints);

        btnDosAp.setText("Dos Aproximació");
        btnDosAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosApActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 169, 0);
        page2.add(btnDosAp, gridBagConstraints);

        btnSortir2.setBackground(new java.awt.Color(153, 153, 153));
        btnSortir2.setText("X");
        btnSortir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortir2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 127, 0, 6);
        page2.add(btnSortir2, gridBagConstraints);

        add(page2, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void IdtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IdtxtFocusGained
        if (Idtxt.getText().equals("Introdueix un identificador numeric")) {
            Idtxt.setText("");
            Idtxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_IdtxtFocusGained

    private void IdtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IdtxtFocusLost
        if (Idtxt.getText().isEmpty()) {
            Idtxt.setText("Introdueix un identificador numeric");
            Idtxt.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_IdtxtFocusLost

    private void IdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdtxtActionPerformed

    private void nomtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomtxtFocusGained
        if (nomtxt.getText().equals("Introdueix un nom")) {
            nomtxt.setText("");
            nomtxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nomtxtFocusGained

    private void nomtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomtxtFocusLost
        if (nomtxt.getText().isEmpty()) {
            nomtxt.setText("Introdueix un nom");
            nomtxt.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_nomtxtFocusLost

    private void nomtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomtxtActionPerformed

    private void colstxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colstxtFocusGained
        if (colstxt.getText().equals("Introdueix el nombre de columnes")) {
            colstxt.setText("");
            colstxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_colstxtFocusGained

    private void colstxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colstxtFocusLost
        if (colstxt.getText().isEmpty()) {
            colstxt.setText("Introdueix el nombre de columnes");
            colstxt.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_colstxtFocusLost

    private void colstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colstxtActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        boolean idValido = validarID();
        boolean nomValido = validarNom();
        boolean numColumnasValido = validarNumColumnes();
        if (idValido && nomValido && numColumnasValido){
            cardLayout.show(cardPanel, "page2");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortirActionPerformed
        // TODO add your handling code here:
//        this.dispose();
    }//GEN-LAST:event_btnSortirActionPerformed

    private void btnDosApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDosApActionPerformed

    private void btnSortir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortir2ActionPerformed
        // TODO add your handling code here:
//        this.dispose();
    }//GEN-LAST:event_btnSortir2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdLabel;
    private javax.swing.JTextField Idtxt;
    private javax.swing.JLabel algoritmeLabel;
    private javax.swing.JRadioButton btnBF;
    private javax.swing.JButton btnCrear;
    private javax.swing.JRadioButton btnDosAp;
    private javax.swing.JButton btnSortir;
    private javax.swing.JButton btnSortir2;
    private javax.swing.JTextField colstxt;
    private javax.swing.JLabel errorId;
    private javax.swing.JLabel errorNcols;
    private javax.swing.JLabel errorNom;
    private javax.swing.JLabel nColsLabel;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField nomtxt;
    private javax.swing.JPanel page1;
    private javax.swing.JPanel page2;
    private javax.swing.JPanel panelGrid;
    private javax.swing.JScrollPane panelProductos;
    private javax.swing.JLabel productesLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
