/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacio;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author ariadna
 */
public class VistaCrearProducte extends javax.swing.JFrame {

    /**
     * Creates new form VistaP
     */
    public VistaCrearProducte() {
        initComponents();                
        infoPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        labelTitol = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        labelId = new javax.swing.JLabel();
        labelFoto = new javax.swing.JLabel();
        botoSortir = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        labelNom = new javax.swing.JLabel();
        textNom = new javax.swing.JTextField();
        labelSimilituds = new javax.swing.JLabel();
        scrollPaneSimilituds = new javax.swing.JScrollPane();
        textAreaSims = new javax.swing.JTextArea();
        textId = new javax.swing.JTextField();
        botoCrear = new javax.swing.JButton();
        botoValidarId = new javax.swing.JButton();
        botoImportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgPanelMouseClicked(evt);
            }
        });

        labelTitol.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        labelTitol.setText("CREAR PRODUCTE");

        labelId.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        labelId.setText("Identificador (ID):");

        labelFoto.setIcon(new javax.swing.ImageIcon("/home/ariadna/Documents/uni/Q5/PROP/PROP_PROYECTO3/subgrup-prop41.1/FONTS/src/main/resources/img/super.png")); // NOI18N
        labelFoto.setText("jLabel1");

        botoSortir.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        botoSortir.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        botoSortir.setText("X");
        botoSortir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoSortir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoSortirMouseClicked(evt);
            }
        });

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));

        labelNom.setText("Nom:");

        textNom.setForeground(new java.awt.Color(153, 153, 153));
        textNom.setText("Introdueix un nom");
        textNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textNomMousePressed(evt);
            }
        });

        labelSimilituds.setText("Similituds amb altres productes (ex., 2:0.75, 3:0.4):");
        labelSimilituds.setFocusable(false);

        textAreaSims.setColumns(20);
        textAreaSims.setForeground(new java.awt.Color(153, 153, 153));
        textAreaSims.setRows(5);
        textAreaSims.setToolTipText("");
        textAreaSims.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textAreaSimsMousePressed(evt);
            }
        });
        scrollPaneSimilituds.setViewportView(textAreaSims);

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addComponent(labelNom)
                .addGap(18, 18, 18)
                .addComponent(textNom))
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addComponent(labelSimilituds)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(scrollPaneSimilituds)
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNom)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(labelSimilituds)
                .addGap(15, 15, 15)
                .addComponent(scrollPaneSimilituds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        textId.setForeground(new java.awt.Color(153, 153, 153));
        textId.setText("Introdueix un identificador numèric");
        textId.setToolTipText("");
        textId.setActionCommand("<Not Set>");
        textId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textIdMousePressed(evt);
            }
        });

        botoCrear.setText("Crear");
        botoCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoCrearMouseClicked(evt);
            }
        });

        botoValidarId.setText("Validar ID");
        botoValidarId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoValidarId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botoValidarIdMousePressed(evt);
            }
        });
        botoValidarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoValidarIdActionPerformed(evt);
            }
        });

        botoImportar.setText("Importar");

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgPanelLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textId, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(bgPanelLayout.createSequentialGroup()
                                                .addComponent(labelId)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(bgPanelLayout.createSequentialGroup()
                                                .addComponent(botoImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botoValidarId)
                                        .addGap(123, 123, 123))))
                            .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addComponent(labelTitol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botoSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelTitol))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botoSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(labelId)
                        .addGap(15, 15, 15)
                        .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(botoValidarId)
                        .addGap(15, 15, 15)
                        .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botoImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(labelFoto)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bgPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgPanelMouseClicked
        if (textId.getText().equals("")) {
            textId.setText("Introdueix un identificador numèric");
            textId.setForeground(Color.gray);
        }
        if ((textNom.getText()).equals("")) {
            textNom.setText("Introdueix un nom");
            textNom.setForeground(Color.gray);
        }
    }//GEN-LAST:event_bgPanelMouseClicked

    private void botoCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoCrearMouseClicked
        String id = textId.getText().trim();
        String nom = textNom.getText().trim();

        if (id.isEmpty() || id.equals("Introdueix un identificador numèric")) {
            JOptionPane.showMessageDialog(this, "Has d'introduir un identificador.", "AVÍS", JOptionPane.WARNING_MESSAGE);
        }
        else {
            if (nom.isEmpty() || nom.equals("Introdueix un nom")) {
                JOptionPane.showMessageDialog(this, "Has d'introduir un nom.", "AVÍS", JOptionPane.WARNING_MESSAGE);
            }
            else {
                if (textAreaSims.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Has d'introduir les similituds amb tots els productes.", "AVÍS", JOptionPane.WARNING_MESSAGE);
                }
                else {
                    JOptionPane.showMessageDialog(null, "S'ha creat el producte correctament!");
                }
            }
        }
    }//GEN-LAST:event_botoCrearMouseClicked

    private void textIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textIdMousePressed
        if (textId.getText().equals("Introdueix un identificador numèric")) {
            textId.setText("");
            textId.setForeground(Color.black);
        }
        if ((textNom.getText()).isEmpty()) {
            textNom.setText("Introdueix un nom");
            textNom.setForeground(Color.gray);
        }
    }//GEN-LAST:event_textIdMousePressed

    private void textAreaSimsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAreaSimsMousePressed
        if (textId.getText().equals("")) {
            textId.setText("Introdueix un identificador numèric");
            textId.setForeground(Color.gray);
        }
        if ((textNom.getText()).equals("")) {
            textNom.setText("Introdueix un nom");
            textNom.setForeground(Color.gray);
        }
        textAreaSims.setForeground(Color.black);
    }//GEN-LAST:event_textAreaSimsMousePressed

    private void textNomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNomMousePressed
        if (textNom.getText().equals("Introdueix un nom")) {
            textNom.setText("");
            textNom.setForeground(Color.black);
        }
        if ((textId.getText()).isEmpty()) {
            textId.setText("Introdueix un identificador numèric");
            textId.setForeground(Color.gray);
        }
    }//GEN-LAST:event_textNomMousePressed

    private void botoSortirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoSortirMouseClicked
        this.dispose();
    }//GEN-LAST:event_botoSortirMouseClicked

    private void botoValidarIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoValidarIdMousePressed
        String id = textId.getText();

        if (id.equals("") || id.equals("Introdueix un identificador numèric")) {
            JOptionPane.showMessageDialog(this, "Has d'introduir un identificador.", "AVÍS", JOptionPane.WARNING_MESSAGE);
        }
        else {  // Comprovar que l'id és vàlid
            try {
                int idNum = Integer.parseInt(id);
                
                if(idNum <= 0) {
                    JOptionPane.showMessageDialog(this, "L'id ha de ser un nombre positiu.", "ATENCIÓ", JOptionPane.WARNING_MESSAGE);
                }
                infoPanel.setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "L'id ha de ser un nombre positiu.", "ATENCIÓ", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_botoValidarIdMousePressed

    private void botoValidarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoValidarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botoValidarIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCrearProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCrearProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCrearProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCrearProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCrearProducte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton botoCrear;
    private javax.swing.JButton botoImportar;
    private javax.swing.JButton botoSortir;
    private javax.swing.JButton botoValidarId;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelSimilituds;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JScrollPane scrollPaneSimilituds;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextArea textAreaSims;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNom;
    // End of variables declaration//GEN-END:variables
}
