/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacio;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author laura
 */
public class VistaLogIn extends javax.swing.JPanel {
    private CtrlPresentacio cp;
    private CardLayout cl;
    private VistaSignUp vistaSU;
    private VistaMenuInici parentMenu;
    /**
     * Creates new form VistaLogIn
     * @param parent
     */
    public VistaLogIn(VistaMenuInici parent) {
        initComponents();
        this.setSize(650, 800);
        cp = new CtrlPresentacio();
        
        cl = new CardLayout();
        bg.setLayout(cl);
        bg.add(LogIn, "logIn");
        cl.show(bg, "logIn");
        this.parentMenu = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        LogIn = new javax.swing.JPanel();
        entrar = new javax.swing.JButton();
        lblContrasenya = new javax.swing.JLabel();
        usuari = new javax.swing.JTextField();
        contrasenya = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblIniciSessio = new javax.swing.JLabel();
        lblUsuari = new javax.swing.JLabel();
        lblRegistrar = new javax.swing.JLabel();
        registre = new javax.swing.JButton();
        logoFoto = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        lblErrors = new javax.swing.JLabel();

        bg.setLayout(new java.awt.CardLayout());

        LogIn.setPreferredSize(new java.awt.Dimension(600, 450));

        entrar.setBackground(new java.awt.Color(157, 213, 184));
        entrar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        entrar.setText("Entrar");
        entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarMouseClicked(evt);
            }
        });
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        lblContrasenya.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        lblContrasenya.setText("CONTRASENYA");

        usuari.setForeground(new java.awt.Color(153, 153, 153));
        usuari.setText("Introdueix el teu nom d'usuari");
        usuari.setBorder(null);
        usuari.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                usuariComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                usuariComponentRemoved(evt);
            }
        });
        usuari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuariMousePressed(evt);
            }
        });
        usuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariActionPerformed(evt);
            }
        });

        contrasenya.setForeground(new java.awt.Color(153, 153, 153));
        contrasenya.setText("********");
        contrasenya.setBorder(null);
        contrasenya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasenyaMousePressed(evt);
            }
        });
        contrasenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenyaActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        lblIniciSessio.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        lblIniciSessio.setText("INICIAR SESSIÓ");

        lblUsuari.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        lblUsuari.setText("USUARI");

        lblRegistrar.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        lblRegistrar.setText("No tens compte?");

        registre.setBackground(new java.awt.Color(255, 211, 147));
        registre.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        registre.setText("Registra't!");
        registre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registreMouseClicked(evt);
            }
        });
        registre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registreActionPerformed(evt);
            }
        });

        logoFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo3.png"))); // NOI18N

        logo1.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        logo1.setText("PRESTATGERIES");

        logo2.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        logo2.setText("N' PRODUCTS");

        lblErrors.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout LogInLayout = new javax.swing.GroupLayout(LogIn);
        LogIn.setLayout(LogInLayout);
        LogInLayout.setHorizontalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInLayout.createSequentialGroup()
                .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo1)
                            .addComponent(logo2)))
                    .addGroup(LogInLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegistrar)
                            .addComponent(registre)))
                    .addGroup(LogInLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LogInLayout.createSequentialGroup()
                                .addComponent(lblContrasenya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entrar)
                            .addComponent(contrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuari, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuari)
                            .addComponent(lblIniciSessio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogInLayout.setVerticalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInLayout.createSequentialGroup()
                .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LogInLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(logo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logo2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(lblIniciSessio)
                .addGap(26, 26, 26)
                .addComponent(lblUsuari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuari, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInLayout.createSequentialGroup()
                        .addComponent(lblErrors)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblContrasenya)
                        .addGap(18, 18, 18)))
                .addComponent(contrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entrar)
                .addGap(8, 8, 8)
                .addComponent(lblRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registre)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        bg.add(LogIn, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseClicked

        try{
            Boolean valid = cp.validarLogin(usuari.getText(), String.valueOf(contrasenya.getPassword()));
            if(String.valueOf(contrasenya.getPassword()).isEmpty() || usuari.getText().isEmpty()){
                lblErrors.setText("S'han de completar tots els camps.");
            }
            else if(usuari.getText().equals("Introdueix el teu nom d'usuari") || String.valueOf(contrasenya.getPassword()).equals("********")){
                lblErrors.setText("S'han de completar tots els camps.");
            }
            else if(!valid){
                boolean existeix = cp.existeixUsuari(usuari.getText());
                if(!existeix){
                    javax.swing.JOptionPane.showMessageDialog(this, "ERROR \nIntent d'inici de sessió incorrecte.\nComprova el teu username.\nNo existeix cap compte amb aquest usuari.\nSi no tens compte registra't!");
                }
                else{
                    javax.swing.JOptionPane.showMessageDialog(this, "ERROR \nIntent d'inici de sessió incorrecte.\nLa contrasenya NO és correcta!");
                }
            }
            else{
                cp.realizarLogin(usuari.getText(), String.valueOf(contrasenya.getPassword()));
                cp.mostrarMenuUsuari();
                this.setVisible(false);
                parentMenu.dispose();
            }
        }
        catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "No s'ha pogut fer l'inici de sessió: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            
            
            
        }
        

    }//GEN-LAST:event_entrarMouseClicked

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarActionPerformed

    private void usuariComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_usuariComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariComponentAdded

    private void usuariComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_usuariComponentRemoved

    }//GEN-LAST:event_usuariComponentRemoved

    private void usuariMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariMousePressed
        if(usuari.getText().equals("Introdueix el teu nom d'usuari")){
            usuari.setText("");
            usuari.setForeground(Color.black);
        }
        if(String.valueOf(contrasenya.getPassword()).isEmpty()){
            contrasenya.setText("********");
            contrasenya.setForeground(Color.gray);
        }
        lblErrors.setText("");
    }//GEN-LAST:event_usuariMousePressed

    private void usuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariActionPerformed

    }//GEN-LAST:event_usuariActionPerformed

    private void contrasenyaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenyaMousePressed
        if(String.valueOf(contrasenya.getPassword()).equals("********")){
            contrasenya.setText("");
            contrasenya.setForeground(Color.black);
        }
        if(usuari.getText().isEmpty()){
            usuari.setText("Introdueix el teu nom d'usuari");
            usuari.setForeground(Color.gray);
        }
        lblErrors.setText("");
    }//GEN-LAST:event_contrasenyaMousePressed

    private void contrasenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenyaActionPerformed

    private void registreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registreMouseClicked
      
    }//GEN-LAST:event_registreMouseClicked

    private void registreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registreActionPerformed
        if(vistaSU == null){
            vistaSU = new VistaSignUp(parentMenu);
            bg.add(vistaSU, "vistaSignUp");
        }
        cl.show(bg, "vistaSignUp");
    }//GEN-LAST:event_registreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LogIn;
    private javax.swing.JPanel bg;
    private javax.swing.JPasswordField contrasenya;
    private javax.swing.JButton entrar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContrasenya;
    private javax.swing.JLabel lblErrors;
    private javax.swing.JLabel lblIniciSessio;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblUsuari;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel logoFoto;
    private javax.swing.JButton registre;
    private javax.swing.JTextField usuari;
    // End of variables declaration//GEN-END:variables
}
