package Presentacio;

import java.awt.CardLayout;
import java.awt.GridLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author ariadna
 */
public class VistaProducte extends javax.swing.JPanel {
    
    private CtrlPresentacio cp;
    private CardLayout cardLayout;
    private JPanel cardPanel;
    private JPanel panelGrid;

    /**
     * Creates new form PanelPrueba
     */
    public VistaProducte() {
        initComponents();
        cp = new CtrlPresentacio();
        this.setSize(700, 500);
        infoPanel.setVisible(false);
        editarPanel.setVisible(false);
        cardLayout = (CardLayout) this.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        llistaPanel = new javax.swing.JPanel();
        labelTitolLlista = new javax.swing.JLabel();
        separatorLlista = new javax.swing.JSeparator();
        botoEsborrarLlista = new javax.swing.JButton();
        botoEditarLlista = new javax.swing.JButton();
        botoCrear = new javax.swing.JButton();
        botoConsultar = new javax.swing.JButton();
        scrollPaneLlista = new javax.swing.JScrollPane();
        productesPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        labelTitolInfo = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        comboBoxPrestatgeria = new javax.swing.JComboBox<>();
        labelSelecPres = new javax.swing.JLabel();
        botoConsultarPosicio = new javax.swing.JButton();
        labelSimilituds = new javax.swing.JLabel();
        separatorInfo = new javax.swing.JSeparator();
        botoSortir = new javax.swing.JButton();
        textIdInfo = new javax.swing.JTextField();
        textNomInfo = new javax.swing.JTextField();
        scrollPaneProductes = new javax.swing.JScrollPane();
        llistaProductes = new javax.swing.JList<>();
        labelSeleccionarProducte = new javax.swing.JLabel();
        botoConsultarSimilitud = new javax.swing.JButton();
        botoEditar = new javax.swing.JButton();
        botoEsborrar = new javax.swing.JButton();
        textPos = new javax.swing.JTextField();
        labelFormat = new javax.swing.JLabel();
        textSimilitud = new javax.swing.JTextField();
        editarPanel = new javax.swing.JPanel();
        labelTitolEditar = new javax.swing.JLabel();
        separatorEditar = new javax.swing.JSeparator();
        labelNouId = new javax.swing.JLabel();
        labelNouNom = new javax.swing.JLabel();
        textNouId = new javax.swing.JTextField();
        textNouNom = new javax.swing.JTextField();
        botoGuardar = new javax.swing.JButton();
        botoSortirEditar = new javax.swing.JButton();
        scrollPaneProductesEditar = new javax.swing.JScrollPane();
        llistaProductesEditar = new javax.swing.JList<>();
        labelSeleccionarProducteEditar = new javax.swing.JLabel();
        labelSimilitudsEditar = new javax.swing.JLabel();
        labelNovaSimilitud = new javax.swing.JLabel();
        textNovaSimilitud = new javax.swing.JTextField();
        labelInfo = new javax.swing.JLabel();
        labelSeleccionarAlgoritme = new javax.swing.JLabel();
        radioBotoFB = new javax.swing.JRadioButton();
        radioBotoDosA = new javax.swing.JRadioButton();

        setLayout(new java.awt.CardLayout());

        llistaPanel.setBackground(new java.awt.Color(255, 255, 255));

        labelTitolLlista.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        labelTitolLlista.setText("LLISTA DE PRODUCTES");

        botoEsborrarLlista.setText("Esborrar");

        botoEditarLlista.setText("Editar");

        botoCrear.setText("Crear");

        botoConsultar.setText("Consultar");
        botoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoConsultarActionPerformed(evt);
            }
        });

        productesPanel.setLayout(new java.awt.GridLayout());
        scrollPaneLlista.setViewportView(productesPanel);

        javax.swing.GroupLayout llistaPanelLayout = new javax.swing.GroupLayout(llistaPanel);
        llistaPanel.setLayout(llistaPanelLayout);
        llistaPanelLayout.setHorizontalGroup(
            llistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, llistaPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(llistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorLlista)
                    .addGroup(llistaPanelLayout.createSequentialGroup()
                        .addGroup(llistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitolLlista)
                            .addGroup(llistaPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(scrollPaneLlista, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(llistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botoCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botoConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(botoEsborrarLlista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botoEditarLlista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );
        llistaPanelLayout.setVerticalGroup(
            llistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(llistaPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelTitolLlista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorLlista, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(llistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(llistaPanelLayout.createSequentialGroup()
                        .addComponent(botoConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(botoCrear)
                        .addGap(18, 18, 18)
                        .addComponent(botoEditarLlista)
                        .addGap(208, 208, 208)
                        .addComponent(botoEsborrarLlista))
                    .addComponent(scrollPaneLlista, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 57, Short.MAX_VALUE))
        );

        add(llistaPanel, "card3");

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));

        labelTitolInfo.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        labelTitolInfo.setText("INFORMACIÓ DEL PRODUCTE");

        labelId.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        labelId.setText("Identificador (ID):");

        labelNom.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        labelNom.setText("Nom:");

        comboBoxPrestatgeria.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        comboBoxPrestatgeria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prestatgeria 1", "Prestatgeria 2", "Prestatgeria 3", "Prestatgeria 4" }));
        comboBoxPrestatgeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPrestatgeriaActionPerformed(evt);
            }
        });

        labelSelecPres.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        labelSelecPres.setText("Selecciona una prestatgeria:");

        botoConsultarPosicio.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        botoConsultarPosicio.setText("Consultar posició");
        botoConsultarPosicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoConsultarPosicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoConsultarPosicioActionPerformed(evt);
            }
        });

        labelSimilituds.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        labelSimilituds.setText("Similituds amb altres productes:");

        botoSortir.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        botoSortir.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        botoSortir.setText("X");
        botoSortir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoSortirActionPerformed(evt);
            }
        });

        textIdInfo.setEditable(false);

        textNomInfo.setEditable(false);
        textNomInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomInfoActionPerformed(evt);
            }
        });

        llistaProductes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Producte 1", "Producte 2", "Producte 3", "Producte 4", "Producte 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        llistaProductes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        scrollPaneProductes.setViewportView(llistaProductes);

        labelSeleccionarProducte.setText("Selecciona un producte:");

        botoConsultarSimilitud.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        botoConsultarSimilitud.setText("Consultar similitud");
        botoConsultarSimilitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoConsultarSimilitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoConsultarSimilitudActionPerformed(evt);
            }
        });

        botoEditar.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        botoEditar.setText("Editar");
        botoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoEditarActionPerformed(evt);
            }
        });

        botoEsborrar.setBackground(new java.awt.Color(255, 51, 51));
        botoEsborrar.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        botoEsborrar.setText("Esborrar");
        botoEsborrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoEsborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoEsborrarMouseClicked(evt);
            }
        });
        botoEsborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoEsborrarActionPerformed(evt);
            }
        });

        textPos.setEditable(false);

        labelFormat.setText("Format: Fila, Columna");

        textSimilitud.setEditable(false);

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(comboBoxPrestatgeria, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelSelecPres))
                        .addGap(77, 77, 77)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(textPos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelFormat))
                            .addComponent(botoConsultarPosicio))
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(scrollPaneProductes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textSimilitud, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botoConsultarSimilitud)))
                            .addComponent(labelSeleccionarProducte)
                            .addComponent(labelSimilituds, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 254, Short.MAX_VALUE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(labelTitolInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botoSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(separatorInfo)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(infoPanelLayout.createSequentialGroup()
                                        .addComponent(labelId)
                                        .addGap(18, 18, 18)
                                        .addComponent(textIdInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                                    .addGroup(infoPanelLayout.createSequentialGroup()
                                        .addComponent(labelNom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textNomInfo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botoEsborrar, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))))
                        .addGap(25, 25, 25))))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelTitolInfo))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botoSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textIdInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelId))
                        .addGap(20, 20, 20)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNom)
                            .addComponent(textNomInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(botoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSelecPres)
                    .addComponent(botoConsultarPosicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxPrestatgeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelFormat)))
                .addGap(31, 31, 31)
                .addComponent(labelSimilituds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSeleccionarProducte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(scrollPaneProductes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(botoEsborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(botoConsultarSimilitud)
                        .addGap(18, 18, 18)
                        .addComponent(textSimilitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        add(infoPanel, "card2");

        editarPanel.setBackground(new java.awt.Color(255, 255, 255));

        labelTitolEditar.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        labelTitolEditar.setText("EDITAR PRODUCTE");

        labelNouId.setText("Nou identificador:");

        labelNouNom.setText("Nou nom:");

        textNouId.setForeground(new java.awt.Color(153, 153, 153));
        textNouId.setText("Introdueix un nou identificador");
        textNouId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNouIdActionPerformed(evt);
            }
        });

        textNouNom.setForeground(new java.awt.Color(153, 153, 153));
        textNouNom.setText("Introdueix un nou nom");
        textNouNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNouNomActionPerformed(evt);
            }
        });

        botoGuardar.setText("Guardar");

        botoSortirEditar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        botoSortirEditar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        botoSortirEditar.setText("X");
        botoSortirEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoSortirEditarActionPerformed(evt);
            }
        });

        llistaProductesEditar.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Producte 1", "Producte 2", "Producte 3", "Producte 4", "Producte 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        llistaProductesEditar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        scrollPaneProductesEditar.setViewportView(llistaProductesEditar);

        labelSeleccionarProducteEditar.setText("Selecciona un producte:");

        labelSimilitudsEditar.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        labelSimilitudsEditar.setText("Similituds amb altres productes:");

        labelNovaSimilitud.setText("Nova similitud:");

        textNovaSimilitud.setForeground(new java.awt.Color(153, 153, 153));
        textNovaSimilitud.setText("Introdueix una nova similitud");

        labelInfo.setText("Si modifiques una similitud, s'ha de recalcular la disposició de les prestatgeries on està! ");

        labelSeleccionarAlgoritme.setText("Selecciona un algoritme:");

        radioBotoFB.setText("Força Bruta");

        radioBotoDosA.setText("Dos Aproximació");

        javax.swing.GroupLayout editarPanelLayout = new javax.swing.GroupLayout(editarPanel);
        editarPanel.setLayout(editarPanelLayout);
        editarPanelLayout.setHorizontalGroup(
            editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editarPanelLayout.createSequentialGroup()
                        .addComponent(labelTitolEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botoSortirEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(editarPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editarPanelLayout.createSequentialGroup()
                                .addGroup(editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editarPanelLayout.createSequentialGroup()
                                        .addGroup(editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelSeleccionarProducteEditar)
                                            .addComponent(scrollPaneProductesEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelSimilitudsEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(49, 49, 49)
                                        .addGroup(editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNovaSimilitud)
                                            .addComponent(textNovaSimilitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(editarPanelLayout.createSequentialGroup()
                                        .addComponent(labelSeleccionarAlgoritme)
                                        .addGap(36, 36, 36)
                                        .addComponent(radioBotoFB)
                                        .addGap(39, 39, 39)
                                        .addComponent(radioBotoDosA))
                                    .addComponent(labelInfo))
                                .addContainerGap(75, Short.MAX_VALUE))
                            .addGroup(editarPanelLayout.createSequentialGroup()
                                .addGroup(editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelNouNom)
                                    .addComponent(labelNouId)
                                    .addComponent(textNouId, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(textNouNom))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botoGuardar)
                                .addGap(41, 41, 41))))
                    .addGroup(editarPanelLayout.createSequentialGroup()
                        .addComponent(separatorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        editarPanelLayout.setVerticalGroup(
            editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarPanelLayout.createSequentialGroup()
                .addGroup(editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editarPanelLayout.createSequentialGroup()
                        .addGroup(editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editarPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(labelTitolEditar))
                            .addGroup(editarPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botoSortirEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separatorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(labelNouId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNouId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editarPanelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(botoGuardar)))
                .addGap(18, 18, 18)
                .addComponent(labelNouNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNouNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSimilitudsEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeleccionarProducteEditar)
                    .addComponent(labelNovaSimilitud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNovaSimilitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPaneProductesEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeleccionarAlgoritme)
                    .addComponent(radioBotoFB)
                    .addComponent(radioBotoDosA))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        add(editarPanel, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void botoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoConsultarActionPerformed
        cardLayout.show(cardPanel, "infoPanel");
    }//GEN-LAST:event_botoConsultarActionPerformed

    private void comboBoxPrestatgeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPrestatgeriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPrestatgeriaActionPerformed

    private void botoConsultarPosicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoConsultarPosicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botoConsultarPosicioActionPerformed

    private void botoSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoSortirActionPerformed
        //this.dispose();
    }//GEN-LAST:event_botoSortirActionPerformed

    private void textNomInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomInfoActionPerformed

    private void botoConsultarSimilitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoConsultarSimilitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botoConsultarSimilitudActionPerformed

    private void botoEsborrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoEsborrarMouseClicked
        int resultat = JOptionPane.showConfirmDialog(this, "Esteu segur que voleu esborrar aquest producte?\nSi l'esborreu, s'eliminaran totes les prestatgeries on estigui aquest producte.\nInfo: Yes (Sí)", "ATENCIÓ!", JOptionPane.YES_NO_OPTION);
        if (resultat == JOptionPane.YES_OPTION) {
            // L'usuari confirma que vol esborrar el producte
            //      cp.esborrarProducte(idProd);
            //      setVisible(false);
            //      dispose();
            //      cp.mostraMenuUsuari();
            JOptionPane.showMessageDialog(this, "El producte s'ha esborrat correctament.", "MISSATGE", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botoEsborrarMouseClicked

    private void botoEsborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoEsborrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botoEsborrarActionPerformed

    private void textNouIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNouIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNouIdActionPerformed

    private void textNouNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNouNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNouNomActionPerformed

    private void botoSortirEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoSortirEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botoSortirEditarActionPerformed

    private void botoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoEditarActionPerformed
        cardLayout.show(cardPanel, "editarPanel");
    }//GEN-LAST:event_botoEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoConsultar;
    private javax.swing.JButton botoConsultarPosicio;
    private javax.swing.JButton botoConsultarSimilitud;
    private javax.swing.JButton botoCrear;
    private javax.swing.JButton botoEditar;
    private javax.swing.JButton botoEditarLlista;
    private javax.swing.JButton botoEsborrar;
    private javax.swing.JButton botoEsborrarLlista;
    private javax.swing.JButton botoGuardar;
    private javax.swing.JButton botoSortir;
    private javax.swing.JButton botoSortirEditar;
    private javax.swing.JComboBox<String> comboBoxPrestatgeria;
    private javax.swing.JPanel editarPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel labelFormat;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelNouId;
    private javax.swing.JLabel labelNouNom;
    private javax.swing.JLabel labelNovaSimilitud;
    private javax.swing.JLabel labelSelecPres;
    private javax.swing.JLabel labelSeleccionarAlgoritme;
    private javax.swing.JLabel labelSeleccionarProducte;
    private javax.swing.JLabel labelSeleccionarProducteEditar;
    private javax.swing.JLabel labelSimilituds;
    private javax.swing.JLabel labelSimilitudsEditar;
    private javax.swing.JLabel labelTitolEditar;
    private javax.swing.JLabel labelTitolInfo;
    private javax.swing.JLabel labelTitolLlista;
    private javax.swing.JPanel llistaPanel;
    private javax.swing.JList<String> llistaProductes;
    private javax.swing.JList<String> llistaProductesEditar;
    private javax.swing.JPanel productesPanel;
    private javax.swing.JRadioButton radioBotoDosA;
    private javax.swing.JRadioButton radioBotoFB;
    private javax.swing.JScrollPane scrollPaneLlista;
    private javax.swing.JScrollPane scrollPaneProductes;
    private javax.swing.JScrollPane scrollPaneProductesEditar;
    private javax.swing.JSeparator separatorEditar;
    private javax.swing.JSeparator separatorInfo;
    private javax.swing.JSeparator separatorLlista;
    private javax.swing.JTextField textIdInfo;
    private javax.swing.JTextField textNomInfo;
    private javax.swing.JTextField textNouId;
    private javax.swing.JTextField textNouNom;
    private javax.swing.JTextField textNovaSimilitud;
    private javax.swing.JTextField textPos;
    private javax.swing.JTextField textSimilitud;
    // End of variables declaration//GEN-END:variables
}
