package Presentacio;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import Exceptions.DominiException;
import Exceptions.PersistenciaException;
import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author guill
 */
public class VistaMenuUsuari extends javax.swing.JFrame {

    private CtrlPresentacio cp;

    /**
     * Creates new form VistaMenuUsuari
     */
    public VistaMenuUsuari() {
        cp = new CtrlPresentacio();
        initComponents();
        initContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initContent() {
        ShowJPanel(new MenuBenvingudaPanel());
    }

    private void ShowJPanel(JPanel p) {
        p.setSize(800, 800);
        p.setLocation(0, 0);
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        botoSobreNosaltres = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        botoEstanterias = new javax.swing.JButton();
        botoProductes = new javax.swing.JButton();
        botoTancarSessio = new javax.swing.JButton();
        titol1 = new javax.swing.JLabel();
        titol2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1120, 830));

        leftPanel.setBackground(new java.awt.Color(200, 255, 200));

        botoSobreNosaltres.setBackground(new java.awt.Color(200, 255, 200));
        botoSobreNosaltres.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        botoSobreNosaltres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nosaltres3.png"))); // NOI18N
        botoSobreNosaltres.setText("     Sobre nosaltres");
        botoSobreNosaltres.setBorder(null);
        botoSobreNosaltres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoSobreNosaltres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoSobreNosaltresActionPerformed(evt);
            }
        });

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoSinBordes2.png"))); // NOI18N
        logoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        logoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoLabelMouseClicked(evt);
            }
        });

        botoEstanterias.setBackground(new java.awt.Color(200, 255, 200));
        botoEstanterias.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        botoEstanterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estante3.png"))); // NOI18N
        botoEstanterias.setText("     Prestatgeria       ");
        botoEstanterias.setBorder(null);
        botoEstanterias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoEstanterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoEstanteriasActionPerformed(evt);
            }
        });

        botoProductes.setBackground(new java.awt.Color(200, 255, 200));
        botoProductes.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        botoProductes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito3.png"))); // NOI18N
        botoProductes.setText("     Productes           ");
        botoProductes.setBorder(null);
        botoProductes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoProductes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoProductesActionPerformed(evt);
            }
        });

        botoTancarSessio.setBackground(new java.awt.Color(200, 255, 200));
        botoTancarSessio.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        botoTancarSessio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/surt3.png"))); // NOI18N
        botoTancarSessio.setText("     Tancar Sessió   ");
        botoTancarSessio.setBorder(null);
        botoTancarSessio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoTancarSessio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoTancarSessioActionPerformed(evt);
            }
        });

        titol1.setFont(new java.awt.Font("Microsoft YaHei", 1, 23)); // NOI18N
        titol1.setForeground(new java.awt.Color(240, 171, 68));
        titol1.setText("PRESTATGERIES");
        titol1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titol1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titol1MouseClicked(evt);
            }
        });

        titol2.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        titol2.setForeground(new java.awt.Color(69, 155, 107));
        titol2.setText("N' PRODUCTS");
        titol2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titol2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titol2MouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(200, 255, 200));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user3.png"))); // NOI18N
        jButton1.setText("      Usuari                ");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titol2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titol1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
            .addComponent(botoEstanterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botoProductes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botoSobreNosaltres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botoTancarSessio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoLabel))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(titol1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titol2)))
                .addGap(18, 18, 18)
                .addComponent(botoEstanterias, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botoProductes, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botoSobreNosaltres, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botoTancarSessio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        content.setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoSobreNoasaltresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoSobreNoasaltresActionPerformed
        ShowJPanel(new MenuAboutUs());
    }//GEN-LAST:event_botoSobreNoasaltresActionPerformed

    private void botoTancarSessioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoTancarSessioActionPerformed
        try {        
            cp.logout();
        } catch (PersistenciaException | DominiException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
            "Error al tancar la sessió :(",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
        cp.mostrarMenuInici();
    }//GEN-LAST:event_botoTancarSessioActionPerformed

    private void botoSobreNosaltresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoSobreNosaltresActionPerformed
        ShowJPanel(new MenuAboutUs());
    }//GEN-LAST:event_botoSobreNosaltresActionPerformed

    private void botoProductesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoProductesActionPerformed
        ShowJPanel(new VistaProducte());
    }//GEN-LAST:event_botoProductesActionPerformed

    private void logoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoLabelMouseClicked
        ShowJPanel(new MenuBenvingudaPanel());
    }//GEN-LAST:event_logoLabelMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        ShowJPanel(new MenuBenvingudaPanel());
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        ShowJPanel(new MenuBenvingudaPanel());
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ShowJPanel(new MenuUsuariPanel());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botoEstanteriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoEstanteriasActionPerformed
        ShowJPanel(new VistaPrestatgeria());
    }//GEN-LAST:event_botoEstanteriasActionPerformed

    private void titol1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titol1MouseClicked
        ShowJPanel(new MenuBenvingudaPanel());
    }//GEN-LAST:event_titol1MouseClicked

    private void titol2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titol2MouseClicked
        ShowJPanel(new MenuBenvingudaPanel());
    }//GEN-LAST:event_titol2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        FlatLightFlatIJTheme.setup();
        UIManager.put( "Button.arc", 20 );
        UIManager.put( "Component.arc", 20 );
        UIManager.put( "CheckBox.arc", 2 );
        UIManager.put( "TextComponent.arc", 20 );
        UIManager.put( "Component.arrowType", "triangle" );
        //UIManager.put("Label.font", new Font("Roboto", Font.BOLD, 22));
        //UIManager.put("TextField.font", new Font("Roboto", Font.PLAIN, 12));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuUsuari().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoEstanterias;
    private javax.swing.JButton botoProductes;
    private javax.swing.JButton botoSobreNosaltres;
    private javax.swing.JButton botoTancarSessio;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel titol1;
    private javax.swing.JLabel titol2;
    // End of variables declaration//GEN-END:variables
}
