/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacio;

import java.awt.Color;

/**
 *
 * @author laura
 */
public class VistaLogIn extends javax.swing.JPanel {

    /**
     * Creates new form vistaLogIn
     */
    public VistaLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortir = new javax.swing.JButton();
        logoFoto = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        lblIniciSessio = new javax.swing.JLabel();
        lblUsuari = new javax.swing.JLabel();
        lblContrasenya = new javax.swing.JLabel();
        usuari = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        contrasenya = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        entrar = new javax.swing.JButton();
        lblErrors = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 400));

        sortir.setBackground(new java.awt.Color(255, 153, 153));
        sortir.setText("Sortir");
        sortir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortirMouseClicked(evt);
            }
        });

        logoFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoFoto.setIcon(new javax.swing.ImageIcon("/home/laura/Documentos/PROP/Proyecto22/subgrup-prop41.1/FONTS/src/main/resources/img/logo3.png")); // NOI18N

        logo1.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        logo1.setText("PRESTATGERIES");

        logo2.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        logo2.setText("N' PRODUCTS");

        lblIniciSessio.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        lblIniciSessio.setText("INICIAR SESSIÓ");

        lblUsuari.setText("USUARI");

        lblContrasenya.setText("CONTRASENYA");

        usuari.setForeground(new java.awt.Color(153, 153, 153));
        usuari.setText("  Introdueix el teu nom d'usuari");
        usuari.setBorder(null);
        usuari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuariMousePressed(evt);
            }
        });
        usuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        contrasenya.setForeground(new java.awt.Color(153, 153, 153));
        contrasenya.setText("********");
        contrasenya.setBorder(null);
        contrasenya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasenyaMousePressed(evt);
            }
        });
        contrasenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenyaActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        entrar.setBackground(new java.awt.Color(157, 213, 184));
        entrar.setText("Entrar");
        entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarMouseClicked(evt);
            }
        });
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        lblErrors.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortir)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblErrors, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contrasenya, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContrasenya, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuari, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIniciSessio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(118, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(logo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logo2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblIniciSessio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuari, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContrasenya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblErrors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortir)
                    .addComponent(entrar))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sortirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortirMouseClicked
        
        
    }//GEN-LAST:event_sortirMouseClicked

    private void usuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariActionPerformed

    private void contrasenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenyaActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarActionPerformed

    private void usuariMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariMousePressed
        if(usuari.getText().equals("  Introdueix el teu nom d'usuari")){
            usuari.setText("");
            usuari.setForeground(Color.black);
        }
        if(String.valueOf(contrasenya.getPassword()).isEmpty()){
            contrasenya.setText("********");
            contrasenya.setForeground(Color.gray);
        }
        lblErrors.setText("");
    }//GEN-LAST:event_usuariMousePressed

    private void contrasenyaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenyaMousePressed
        if(String.valueOf(contrasenya.getPassword()).equals("********")){
            contrasenya.setText("");
            contrasenya.setForeground(Color.black);
        }
        if(usuari.getText().isEmpty()){
            usuari.setText(" Introdueix el teu nom d'usuari");
            usuari.setForeground(Color.gray);
        }
        lblErrors.setText("");
    }//GEN-LAST:event_contrasenyaMousePressed

    private void entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseClicked
        
        //....
        //Si el usuario y/o la contraseña estan mal entonces: 
        //if(....){
       // javax.swing.JOptionPane.showMessageDialog(this, "ERROR \nIntent d'inici de sessió incorrecte.\n No existeix cap compte amb aquest usuari i/o contrasenya.");
       if(String.valueOf(contrasenya.getPassword()).isEmpty() || usuari.getText().isEmpty()){
            lblErrors.setText("S'han de completar tots els camps.");
        }
       
       if(usuari.getText().equals("  Introdueix el teu nom d'usuari") || String.valueOf(contrasenya.getPassword()).equals("********")){
            lblErrors.setText("S'han de completar tots els camps.");
        }
    }//GEN-LAST:event_entrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasenya;
    private javax.swing.JButton entrar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContrasenya;
    private javax.swing.JLabel lblErrors;
    private javax.swing.JLabel lblIniciSessio;
    private javax.swing.JLabel lblUsuari;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel logoFoto;
    private javax.swing.JButton sortir;
    private javax.swing.JTextField usuari;
    // End of variables declaration//GEN-END:variables
}
